Repository octopusdownloader/octopusdownloader, pull requests merged in 2018-12, with the labels that each got.

#35 Feature/add settings proxy class
  src/main/java/org/octopus/Main.java
  src/main/java/org/octopus/core/Downloadable.java
  src/main/java/org/octopus/core/Downloader.java
  src/main/java/org/octopus/core/http/HTTPDownload.java
  src/main/java/org/octopus/core/http/HTTPException.java
  src/main/java/org/octopus/core/http/HTTPInspector.java
  src/main/java/org/octopus/core/http/HTTPOutOfRangeException.java
  src/main/java/org/octopus/core/http/HTTPUtils.java
  src/main/java/org/octopus/core/http/RedirectException.java
  src/main/java/org/octopus/core/http/RedirectLimitException.java
  src/main/java/org/octopus/core/proxy/ProxySetting.java
  src/main/java/org/octopus/settings/OctopusSettings.java
  src/test/java/org/octopus/core/DownloaderUnitTest.java
  src/test/java/org/octopus/core/http/HTTPDownloadTest.java
  src/test/java/org/octopus/core/http/HTTPInspectorTest.java
  src/test/java/org/octopus/core/http/HTTPTestSuite.java
  src/test/java/org/octopus/core/http/HTTPUtilsUnitTest.java
Labels: core, enhancement, in progress, stability

#41 Open at same location
  src/main/java/org/octopus/dialogs/newdownload/AddNewDownloadController.java
  src/main/resources/scenes/dialogs/new-download-dialog.fxml
Labels: UI/UX, enhancement

#42 Util/filehandler
  src/main/java/org/octopus/utils/FileMerger.java
  src/test/java/org/octopus/utils/FileMergerUnitTest.java
Labels: core, enhancement
