Repository octopusdownloader/octopusdownloader, pull requests merged in 2018-11, with the labels that each got.

#25 Add Travis Mac with Appveyor
  .travis.yml
  appveyor.yml
  build.gradle
Labels: CI/CD, enhancement

#30 removed deprecated code
  src/main/java/com/octopus/Downloader/DownloadWorker.java
  src/main/java/com/octopus/Downloader/Downloader.java
  src/main/java/com/octopus/Downloader/HttpDownloadWorker.java
Labels: core

#27 Proxy
  src/main/java/com/octopus/core/http/HTTPInspector.java
  src/main/java/com/octopus/core/proxy/ProxySetting.java
  src/test/java/com/octopus/core/http/HTTPDownloadTest.java
  src/test/java/com/octopus/core/http/HTTPInspectorTest.java
Labels: core, enhancement

#22 gui basic
  src/main/resources/images/1125156.png
  src/main/resources/images/kisspng-computer-icons-youtube-play-button-clip-art-icon-png-play-button-5ab1113388a855.8771330715215537155598.jpg
  src/main/resources/images/octopus.png
  src/main/resources/images/pause-512.png
  src/main/resources/images/pause.png
  src/main/resources/images/play.jpg
  src/main/resources/scenes/MainController.java
  src/main/resources/scenes/NewDownloadController.java
  src/main/resources/scenes/new-download-dialog.fxml
  src/main/resources/scenes/octopus.fxml
Labels: UI/UX, enhancement

#31 fixed fxml errors
  src/main/resources/scenes/MainController.java
  src/main/resources/scenes/NewDownloadController.java
  src/main/resources/scenes/octopus.fxml
Labels: bug, in progress
